// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v26.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsStoreKit2Messages(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashStoreKit2Messages(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsStoreKit2Messages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsStoreKit2Messages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsStoreKit2Messages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsStoreKit2Messages(lhsKey, rhsKey) {
          if deepEqualsStoreKit2Messages(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsStoreKit2Messages(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashStoreKit2Messages(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashStoreKit2Messages(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashStoreKit2Messages(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashStoreKit2Messages(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashStoreKit2Messages(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashStoreKit2Messages(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


enum SK2ProductTypeMessage: Int {
  /// A consumable in-app purchase.
  case consumable = 0
  /// A non-consumable in-app purchase.
  case nonConsumable = 1
  /// A non-renewing subscription.
  case nonRenewable = 2
  /// An auto-renewable subscription.
  case autoRenewable = 3
}

enum SK2SubscriptionOfferTypeMessage: Int {
  case introductory = 0
  case promotional = 1
  case winBack = 2
}

enum SK2SubscriptionOfferPaymentModeMessage: Int {
  case payAsYouGo = 0
  case payUpFront = 1
  case freeTrial = 2
}

enum SK2SubscriptionPeriodUnitMessage: Int {
  case day = 0
  case week = 1
  case month = 2
  case year = 3
}

enum SK2ProductPurchaseResultMessage: Int {
  case success = 0
  case unverified = 1
  case userCancelled = 2
  case pending = 3
}

/// The status of a purchase transaction.
/// Used to communicate the result state to Dart layer via purchaseStream.
enum SK2PurchaseStatusMessage: Int {
  /// Purchase completed successfully.
  case purchased = 0
  /// Purchase is pending (e.g., Ask to Buy).
  case pending = 1
  /// Purchase was cancelled by the user.
  case cancelled = 2
  /// Purchase was restored.
  case restored = 3
}

/// Generated class from Pigeon that represents data sent in messages.
struct SK2SubscriptionOfferMessage: Hashable {
  var id: String? = nil
  var price: Double
  var type: SK2SubscriptionOfferTypeMessage
  var period: SK2SubscriptionPeriodMessage
  var periodCount: Int64
  var paymentMode: SK2SubscriptionOfferPaymentModeMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SK2SubscriptionOfferMessage? {
    let id: String? = nilOrValue(pigeonVar_list[0])
    let price = pigeonVar_list[1] as! Double
    let type = pigeonVar_list[2] as! SK2SubscriptionOfferTypeMessage
    let period = pigeonVar_list[3] as! SK2SubscriptionPeriodMessage
    let periodCount = pigeonVar_list[4] as! Int64
    let paymentMode = pigeonVar_list[5] as! SK2SubscriptionOfferPaymentModeMessage

    return SK2SubscriptionOfferMessage(
      id: id,
      price: price,
      type: type,
      period: period,
      periodCount: periodCount,
      paymentMode: paymentMode
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      price,
      type,
      period,
      periodCount,
      paymentMode,
    ]
  }
  static func == (lhs: SK2SubscriptionOfferMessage, rhs: SK2SubscriptionOfferMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsStoreKit2Messages(lhs.id, rhs.id) && deepEqualsStoreKit2Messages(lhs.price, rhs.price) && deepEqualsStoreKit2Messages(lhs.type, rhs.type) && deepEqualsStoreKit2Messages(lhs.period, rhs.period) && deepEqualsStoreKit2Messages(lhs.periodCount, rhs.periodCount) && deepEqualsStoreKit2Messages(lhs.paymentMode, rhs.paymentMode)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SK2SubscriptionOfferMessage")
    deepHashStoreKit2Messages(value: id, hasher: &hasher)
    deepHashStoreKit2Messages(value: price, hasher: &hasher)
    deepHashStoreKit2Messages(value: type, hasher: &hasher)
    deepHashStoreKit2Messages(value: period, hasher: &hasher)
    deepHashStoreKit2Messages(value: periodCount, hasher: &hasher)
    deepHashStoreKit2Messages(value: paymentMode, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SK2SubscriptionPeriodMessage: Hashable {
  /// The number of units that the period represents.
  var value: Int64
  /// The unit of time that this period represents.
  var unit: SK2SubscriptionPeriodUnitMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SK2SubscriptionPeriodMessage? {
    let value = pigeonVar_list[0] as! Int64
    let unit = pigeonVar_list[1] as! SK2SubscriptionPeriodUnitMessage

    return SK2SubscriptionPeriodMessage(
      value: value,
      unit: unit
    )
  }
  func toList() -> [Any?] {
    return [
      value,
      unit,
    ]
  }
  static func == (lhs: SK2SubscriptionPeriodMessage, rhs: SK2SubscriptionPeriodMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsStoreKit2Messages(lhs.value, rhs.value) && deepEqualsStoreKit2Messages(lhs.unit, rhs.unit)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SK2SubscriptionPeriodMessage")
    deepHashStoreKit2Messages(value: value, hasher: &hasher)
    deepHashStoreKit2Messages(value: unit, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SK2SubscriptionInfoMessage: Hashable {
  /// An array of all the promotional offers configured for this subscription.
  var promotionalOffers: [SK2SubscriptionOfferMessage]
  /// The group identifier for this subscription.
  var subscriptionGroupID: String
  /// The duration that this subscription lasts before auto-renewing.
  var subscriptionPeriod: SK2SubscriptionPeriodMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SK2SubscriptionInfoMessage? {
    let promotionalOffers = pigeonVar_list[0] as! [SK2SubscriptionOfferMessage]
    let subscriptionGroupID = pigeonVar_list[1] as! String
    let subscriptionPeriod = pigeonVar_list[2] as! SK2SubscriptionPeriodMessage

    return SK2SubscriptionInfoMessage(
      promotionalOffers: promotionalOffers,
      subscriptionGroupID: subscriptionGroupID,
      subscriptionPeriod: subscriptionPeriod
    )
  }
  func toList() -> [Any?] {
    return [
      promotionalOffers,
      subscriptionGroupID,
      subscriptionPeriod,
    ]
  }
  static func == (lhs: SK2SubscriptionInfoMessage, rhs: SK2SubscriptionInfoMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsStoreKit2Messages(lhs.promotionalOffers, rhs.promotionalOffers) && deepEqualsStoreKit2Messages(lhs.subscriptionGroupID, rhs.subscriptionGroupID) && deepEqualsStoreKit2Messages(lhs.subscriptionPeriod, rhs.subscriptionPeriod)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SK2SubscriptionInfoMessage")
    deepHashStoreKit2Messages(value: promotionalOffers, hasher: &hasher)
    deepHashStoreKit2Messages(value: subscriptionGroupID, hasher: &hasher)
    deepHashStoreKit2Messages(value: subscriptionPeriod, hasher: &hasher)
  }
}

/// A Pigeon message class representing a Product
/// https://developer.apple.com/documentation/storekit/product
///
/// Generated class from Pigeon that represents data sent in messages.
struct SK2ProductMessage: Hashable {
  /// The unique product identifier.
  var id: String
  /// The localized display name of the product, if it exists.
  var displayName: String
  /// The localized description of the product.
  var description: String
  /// The localized string representation of the product price, suitable for display.
  var price: Double
  /// The localized price of the product as a string.
  var displayPrice: String
  /// The types of in-app purchases.
  var type: SK2ProductTypeMessage
  /// The subscription information for an auto-renewable subscription.
  var subscription: SK2SubscriptionInfoMessage? = nil
  /// The currency and locale information for this product
  var priceLocale: SK2PriceLocaleMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SK2ProductMessage? {
    let id = pigeonVar_list[0] as! String
    let displayName = pigeonVar_list[1] as! String
    let description = pigeonVar_list[2] as! String
    let price = pigeonVar_list[3] as! Double
    let displayPrice = pigeonVar_list[4] as! String
    let type = pigeonVar_list[5] as! SK2ProductTypeMessage
    let subscription: SK2SubscriptionInfoMessage? = nilOrValue(pigeonVar_list[6])
    let priceLocale = pigeonVar_list[7] as! SK2PriceLocaleMessage

    return SK2ProductMessage(
      id: id,
      displayName: displayName,
      description: description,
      price: price,
      displayPrice: displayPrice,
      type: type,
      subscription: subscription,
      priceLocale: priceLocale
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      displayName,
      description,
      price,
      displayPrice,
      type,
      subscription,
      priceLocale,
    ]
  }
  static func == (lhs: SK2ProductMessage, rhs: SK2ProductMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsStoreKit2Messages(lhs.id, rhs.id) && deepEqualsStoreKit2Messages(lhs.displayName, rhs.displayName) && deepEqualsStoreKit2Messages(lhs.description, rhs.description) && deepEqualsStoreKit2Messages(lhs.price, rhs.price) && deepEqualsStoreKit2Messages(lhs.displayPrice, rhs.displayPrice) && deepEqualsStoreKit2Messages(lhs.type, rhs.type) && deepEqualsStoreKit2Messages(lhs.subscription, rhs.subscription) && deepEqualsStoreKit2Messages(lhs.priceLocale, rhs.priceLocale)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SK2ProductMessage")
    deepHashStoreKit2Messages(value: id, hasher: &hasher)
    deepHashStoreKit2Messages(value: displayName, hasher: &hasher)
    deepHashStoreKit2Messages(value: description, hasher: &hasher)
    deepHashStoreKit2Messages(value: price, hasher: &hasher)
    deepHashStoreKit2Messages(value: displayPrice, hasher: &hasher)
    deepHashStoreKit2Messages(value: type, hasher: &hasher)
    deepHashStoreKit2Messages(value: subscription, hasher: &hasher)
    deepHashStoreKit2Messages(value: priceLocale, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SK2PriceLocaleMessage: Hashable {
  var currencyCode: String
  var currencySymbol: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SK2PriceLocaleMessage? {
    let currencyCode = pigeonVar_list[0] as! String
    let currencySymbol = pigeonVar_list[1] as! String

    return SK2PriceLocaleMessage(
      currencyCode: currencyCode,
      currencySymbol: currencySymbol
    )
  }
  func toList() -> [Any?] {
    return [
      currencyCode,
      currencySymbol,
    ]
  }
  static func == (lhs: SK2PriceLocaleMessage, rhs: SK2PriceLocaleMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsStoreKit2Messages(lhs.currencyCode, rhs.currencyCode) && deepEqualsStoreKit2Messages(lhs.currencySymbol, rhs.currencySymbol)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SK2PriceLocaleMessage")
    deepHashStoreKit2Messages(value: currencyCode, hasher: &hasher)
    deepHashStoreKit2Messages(value: currencySymbol, hasher: &hasher)
  }
}

/// A Pigeon message class representing a Signature
/// https://developer.apple.com/documentation/storekit/product/subscriptionoffer/signature
///
/// Generated class from Pigeon that represents data sent in messages.
struct SK2SubscriptionOfferSignatureMessage: Hashable {
  var keyID: String
  var nonce: String
  var timestamp: Int64
  var signature: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SK2SubscriptionOfferSignatureMessage? {
    let keyID = pigeonVar_list[0] as! String
    let nonce = pigeonVar_list[1] as! String
    let timestamp = pigeonVar_list[2] as! Int64
    let signature = pigeonVar_list[3] as! String

    return SK2SubscriptionOfferSignatureMessage(
      keyID: keyID,
      nonce: nonce,
      timestamp: timestamp,
      signature: signature
    )
  }
  func toList() -> [Any?] {
    return [
      keyID,
      nonce,
      timestamp,
      signature,
    ]
  }
  static func == (lhs: SK2SubscriptionOfferSignatureMessage, rhs: SK2SubscriptionOfferSignatureMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsStoreKit2Messages(lhs.keyID, rhs.keyID) && deepEqualsStoreKit2Messages(lhs.nonce, rhs.nonce) && deepEqualsStoreKit2Messages(lhs.timestamp, rhs.timestamp) && deepEqualsStoreKit2Messages(lhs.signature, rhs.signature)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SK2SubscriptionOfferSignatureMessage")
    deepHashStoreKit2Messages(value: keyID, hasher: &hasher)
    deepHashStoreKit2Messages(value: nonce, hasher: &hasher)
    deepHashStoreKit2Messages(value: timestamp, hasher: &hasher)
    deepHashStoreKit2Messages(value: signature, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SK2SubscriptionOfferPurchaseMessage: Hashable {
  var promotionalOfferId: String
  var promotionalOfferSignature: SK2SubscriptionOfferSignatureMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SK2SubscriptionOfferPurchaseMessage? {
    let promotionalOfferId = pigeonVar_list[0] as! String
    let promotionalOfferSignature = pigeonVar_list[1] as! SK2SubscriptionOfferSignatureMessage

    return SK2SubscriptionOfferPurchaseMessage(
      promotionalOfferId: promotionalOfferId,
      promotionalOfferSignature: promotionalOfferSignature
    )
  }
  func toList() -> [Any?] {
    return [
      promotionalOfferId,
      promotionalOfferSignature,
    ]
  }
  static func == (lhs: SK2SubscriptionOfferPurchaseMessage, rhs: SK2SubscriptionOfferPurchaseMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsStoreKit2Messages(lhs.promotionalOfferId, rhs.promotionalOfferId) && deepEqualsStoreKit2Messages(lhs.promotionalOfferSignature, rhs.promotionalOfferSignature)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SK2SubscriptionOfferPurchaseMessage")
    deepHashStoreKit2Messages(value: promotionalOfferId, hasher: &hasher)
    deepHashStoreKit2Messages(value: promotionalOfferSignature, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SK2ProductPurchaseOptionsMessage: Hashable {
  var appAccountToken: String? = nil
  var quantity: Int64? = nil
  var promotionalOffer: SK2SubscriptionOfferPurchaseMessage? = nil
  var winBackOfferId: String? = nil
  /// Compact JWS signed by the developer's App Store key asserting whether
  /// this user is eligible for the product's introductory offer. When set
  /// with `eligible=false`, StoreKit suppresses the intro offer for this
  /// purchase. iOS 18.4+ SDK; back-deploys to iOS 15.0 at runtime.
  var introductoryOfferEligibilityJws: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SK2ProductPurchaseOptionsMessage? {
    let appAccountToken: String? = nilOrValue(pigeonVar_list[0])
    let quantity: Int64? = nilOrValue(pigeonVar_list[1])
    let promotionalOffer: SK2SubscriptionOfferPurchaseMessage? = nilOrValue(pigeonVar_list[2])
    let winBackOfferId: String? = nilOrValue(pigeonVar_list[3])
    let introductoryOfferEligibilityJws: String? = nilOrValue(pigeonVar_list[4])

    return SK2ProductPurchaseOptionsMessage(
      appAccountToken: appAccountToken,
      quantity: quantity,
      promotionalOffer: promotionalOffer,
      winBackOfferId: winBackOfferId,
      introductoryOfferEligibilityJws: introductoryOfferEligibilityJws
    )
  }
  func toList() -> [Any?] {
    return [
      appAccountToken,
      quantity,
      promotionalOffer,
      winBackOfferId,
      introductoryOfferEligibilityJws,
    ]
  }
  static func == (lhs: SK2ProductPurchaseOptionsMessage, rhs: SK2ProductPurchaseOptionsMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsStoreKit2Messages(lhs.appAccountToken, rhs.appAccountToken) && deepEqualsStoreKit2Messages(lhs.quantity, rhs.quantity) && deepEqualsStoreKit2Messages(lhs.promotionalOffer, rhs.promotionalOffer) && deepEqualsStoreKit2Messages(lhs.winBackOfferId, rhs.winBackOfferId) && deepEqualsStoreKit2Messages(lhs.introductoryOfferEligibilityJws, rhs.introductoryOfferEligibilityJws)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SK2ProductPurchaseOptionsMessage")
    deepHashStoreKit2Messages(value: appAccountToken, hasher: &hasher)
    deepHashStoreKit2Messages(value: quantity, hasher: &hasher)
    deepHashStoreKit2Messages(value: promotionalOffer, hasher: &hasher)
    deepHashStoreKit2Messages(value: winBackOfferId, hasher: &hasher)
    deepHashStoreKit2Messages(value: introductoryOfferEligibilityJws, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SK2TransactionMessage: Hashable {
  var id: Int64
  var originalId: Int64
  var productId: String
  var purchaseDate: String? = nil
  var expirationDate: String? = nil
  var purchasedQuantity: Int64
  var appAccountToken: String? = nil
  var receiptData: String? = nil
  var error: SK2ErrorMessage? = nil
  var jsonRepresentation: String? = nil
  /// The status of this purchase transaction.
  /// Set by native side to communicate the result state to Dart layer.
  var status: SK2PurchaseStatusMessage


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SK2TransactionMessage? {
    let id = pigeonVar_list[0] as! Int64
    let originalId = pigeonVar_list[1] as! Int64
    let productId = pigeonVar_list[2] as! String
    let purchaseDate: String? = nilOrValue(pigeonVar_list[3])
    let expirationDate: String? = nilOrValue(pigeonVar_list[4])
    let purchasedQuantity = pigeonVar_list[5] as! Int64
    let appAccountToken: String? = nilOrValue(pigeonVar_list[6])
    let receiptData: String? = nilOrValue(pigeonVar_list[7])
    let error: SK2ErrorMessage? = nilOrValue(pigeonVar_list[8])
    let jsonRepresentation: String? = nilOrValue(pigeonVar_list[9])
    let status = pigeonVar_list[10] as! SK2PurchaseStatusMessage

    return SK2TransactionMessage(
      id: id,
      originalId: originalId,
      productId: productId,
      purchaseDate: purchaseDate,
      expirationDate: expirationDate,
      purchasedQuantity: purchasedQuantity,
      appAccountToken: appAccountToken,
      receiptData: receiptData,
      error: error,
      jsonRepresentation: jsonRepresentation,
      status: status
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      originalId,
      productId,
      purchaseDate,
      expirationDate,
      purchasedQuantity,
      appAccountToken,
      receiptData,
      error,
      jsonRepresentation,
      status,
    ]
  }
  static func == (lhs: SK2TransactionMessage, rhs: SK2TransactionMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsStoreKit2Messages(lhs.id, rhs.id) && deepEqualsStoreKit2Messages(lhs.originalId, rhs.originalId) && deepEqualsStoreKit2Messages(lhs.productId, rhs.productId) && deepEqualsStoreKit2Messages(lhs.purchaseDate, rhs.purchaseDate) && deepEqualsStoreKit2Messages(lhs.expirationDate, rhs.expirationDate) && deepEqualsStoreKit2Messages(lhs.purchasedQuantity, rhs.purchasedQuantity) && deepEqualsStoreKit2Messages(lhs.appAccountToken, rhs.appAccountToken) && deepEqualsStoreKit2Messages(lhs.receiptData, rhs.receiptData) && deepEqualsStoreKit2Messages(lhs.error, rhs.error) && deepEqualsStoreKit2Messages(lhs.jsonRepresentation, rhs.jsonRepresentation) && deepEqualsStoreKit2Messages(lhs.status, rhs.status)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SK2TransactionMessage")
    deepHashStoreKit2Messages(value: id, hasher: &hasher)
    deepHashStoreKit2Messages(value: originalId, hasher: &hasher)
    deepHashStoreKit2Messages(value: productId, hasher: &hasher)
    deepHashStoreKit2Messages(value: purchaseDate, hasher: &hasher)
    deepHashStoreKit2Messages(value: expirationDate, hasher: &hasher)
    deepHashStoreKit2Messages(value: purchasedQuantity, hasher: &hasher)
    deepHashStoreKit2Messages(value: appAccountToken, hasher: &hasher)
    deepHashStoreKit2Messages(value: receiptData, hasher: &hasher)
    deepHashStoreKit2Messages(value: error, hasher: &hasher)
    deepHashStoreKit2Messages(value: jsonRepresentation, hasher: &hasher)
    deepHashStoreKit2Messages(value: status, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SK2ErrorMessage: Hashable {
  var code: Int64
  var domain: String
  var userInfo: [String: Any]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SK2ErrorMessage? {
    let code = pigeonVar_list[0] as! Int64
    let domain = pigeonVar_list[1] as! String
    let userInfo: [String: Any]? = nilOrValue(pigeonVar_list[2])

    return SK2ErrorMessage(
      code: code,
      domain: domain,
      userInfo: userInfo
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      domain,
      userInfo,
    ]
  }
  static func == (lhs: SK2ErrorMessage, rhs: SK2ErrorMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsStoreKit2Messages(lhs.code, rhs.code) && deepEqualsStoreKit2Messages(lhs.domain, rhs.domain) && deepEqualsStoreKit2Messages(lhs.userInfo, rhs.userInfo)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SK2ErrorMessage")
    deepHashStoreKit2Messages(value: code, hasher: &hasher)
    deepHashStoreKit2Messages(value: domain, hasher: &hasher)
    deepHashStoreKit2Messages(value: userInfo, hasher: &hasher)
  }
}

private class StoreKit2MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SK2ProductTypeMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SK2SubscriptionOfferTypeMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SK2SubscriptionOfferPaymentModeMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SK2SubscriptionPeriodUnitMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SK2ProductPurchaseResultMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SK2PurchaseStatusMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      return SK2SubscriptionOfferMessage.fromList(self.readValue() as! [Any?])
    case 136:
      return SK2SubscriptionPeriodMessage.fromList(self.readValue() as! [Any?])
    case 137:
      return SK2SubscriptionInfoMessage.fromList(self.readValue() as! [Any?])
    case 138:
      return SK2ProductMessage.fromList(self.readValue() as! [Any?])
    case 139:
      return SK2PriceLocaleMessage.fromList(self.readValue() as! [Any?])
    case 140:
      return SK2SubscriptionOfferSignatureMessage.fromList(self.readValue() as! [Any?])
    case 141:
      return SK2SubscriptionOfferPurchaseMessage.fromList(self.readValue() as! [Any?])
    case 142:
      return SK2ProductPurchaseOptionsMessage.fromList(self.readValue() as! [Any?])
    case 143:
      return SK2TransactionMessage.fromList(self.readValue() as! [Any?])
    case 144:
      return SK2ErrorMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class StoreKit2MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? SK2ProductTypeMessage {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? SK2SubscriptionOfferTypeMessage {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? SK2SubscriptionOfferPaymentModeMessage {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? SK2SubscriptionPeriodUnitMessage {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? SK2ProductPurchaseResultMessage {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? SK2PurchaseStatusMessage {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? SK2SubscriptionOfferMessage {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? SK2SubscriptionPeriodMessage {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? SK2SubscriptionInfoMessage {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? SK2ProductMessage {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? SK2PriceLocaleMessage {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? SK2SubscriptionOfferSignatureMessage {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? SK2SubscriptionOfferPurchaseMessage {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? SK2ProductPurchaseOptionsMessage {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? SK2TransactionMessage {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? SK2ErrorMessage {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class StoreKit2MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return StoreKit2MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return StoreKit2MessagesPigeonCodecWriter(data: data)
  }
}

class StoreKit2MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = StoreKit2MessagesPigeonCodec(readerWriter: StoreKit2MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol InAppPurchase2API {
  func canMakePayments() throws -> Bool
  func products(identifiers: [String], completion: @escaping (Result<[SK2ProductMessage], Error>) -> Void)
  func purchase(id: String, options: SK2ProductPurchaseOptionsMessage?, completion: @escaping (Result<SK2ProductPurchaseResultMessage, Error>) -> Void)
  func isWinBackOfferEligible(productId: String, offerId: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func isIntroductoryOfferEligible(productId: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func transactions(completion: @escaping (Result<[SK2TransactionMessage], Error>) -> Void)
  func unfinishedTransactions(completion: @escaping (Result<[SK2TransactionMessage], Error>) -> Void)
  func finish(id: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  func startListeningToTransactions() throws
  func stopListeningToTransactions() throws
  func restorePurchases(completion: @escaping (Result<Void, Error>) -> Void)
  func countryCode(completion: @escaping (Result<String, Error>) -> Void)
  func sync(completion: @escaping (Result<Void, Error>) -> Void)
  /// Returns the StoreKit2 `AppTransaction` JWS payload's `appTransactionId`,
  /// suitable for use as the `transactionId` claim when minting an
  /// introductory-offer-eligibility JWS for a user who has no prior App
  /// Store transactions. Returns null on iOS < 16.0 (where AppTransaction
  /// is unavailable) or if the AppTransaction is unverified.
  func appTransactionId(completion: @escaping (Result<String?, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class InAppPurchase2APISetup {
  static var codec: FlutterStandardMessageCodec { StoreKit2MessagesPigeonCodec.shared }
  /// Sets up an instance of `InAppPurchase2API` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: InAppPurchase2API?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let canMakePaymentsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.in_app_purchase_storekit.InAppPurchase2API.canMakePayments\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      canMakePaymentsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.canMakePayments()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      canMakePaymentsChannel.setMessageHandler(nil)
    }
    let productsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.in_app_purchase_storekit.InAppPurchase2API.products\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      productsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let identifiersArg = args[0] as! [String]
        api.products(identifiers: identifiersArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      productsChannel.setMessageHandler(nil)
    }
    let purchaseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.in_app_purchase_storekit.InAppPurchase2API.purchase\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      purchaseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        let optionsArg: SK2ProductPurchaseOptionsMessage? = nilOrValue(args[1])
        api.purchase(id: idArg, options: optionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      purchaseChannel.setMessageHandler(nil)
    }
    let isWinBackOfferEligibleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.in_app_purchase_storekit.InAppPurchase2API.isWinBackOfferEligible\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isWinBackOfferEligibleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let productIdArg = args[0] as! String
        let offerIdArg = args[1] as! String
        api.isWinBackOfferEligible(productId: productIdArg, offerId: offerIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isWinBackOfferEligibleChannel.setMessageHandler(nil)
    }
    let isIntroductoryOfferEligibleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.in_app_purchase_storekit.InAppPurchase2API.isIntroductoryOfferEligible\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isIntroductoryOfferEligibleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let productIdArg = args[0] as! String
        api.isIntroductoryOfferEligible(productId: productIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isIntroductoryOfferEligibleChannel.setMessageHandler(nil)
    }
    let transactionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.in_app_purchase_storekit.InAppPurchase2API.transactions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      transactionsChannel.setMessageHandler { _, reply in
        api.transactions { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      transactionsChannel.setMessageHandler(nil)
    }
    let unfinishedTransactionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.in_app_purchase_storekit.InAppPurchase2API.unfinishedTransactions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      unfinishedTransactionsChannel.setMessageHandler { _, reply in
        api.unfinishedTransactions { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      unfinishedTransactionsChannel.setMessageHandler(nil)
    }
    let finishChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.in_app_purchase_storekit.InAppPurchase2API.finish\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      finishChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! Int64
        api.finish(id: idArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      finishChannel.setMessageHandler(nil)
    }
    let startListeningToTransactionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.in_app_purchase_storekit.InAppPurchase2API.startListeningToTransactions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startListeningToTransactionsChannel.setMessageHandler { _, reply in
        do {
          try api.startListeningToTransactions()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startListeningToTransactionsChannel.setMessageHandler(nil)
    }
    let stopListeningToTransactionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.in_app_purchase_storekit.InAppPurchase2API.stopListeningToTransactions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopListeningToTransactionsChannel.setMessageHandler { _, reply in
        do {
          try api.stopListeningToTransactions()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopListeningToTransactionsChannel.setMessageHandler(nil)
    }
    let restorePurchasesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.in_app_purchase_storekit.InAppPurchase2API.restorePurchases\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      restorePurchasesChannel.setMessageHandler { _, reply in
        api.restorePurchases { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      restorePurchasesChannel.setMessageHandler(nil)
    }
    let countryCodeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.in_app_purchase_storekit.InAppPurchase2API.countryCode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      countryCodeChannel.setMessageHandler { _, reply in
        api.countryCode { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      countryCodeChannel.setMessageHandler(nil)
    }
    let syncChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.in_app_purchase_storekit.InAppPurchase2API.sync\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      syncChannel.setMessageHandler { _, reply in
        api.sync { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      syncChannel.setMessageHandler(nil)
    }
    /// Returns the StoreKit2 `AppTransaction` JWS payload's `appTransactionId`,
    /// suitable for use as the `transactionId` claim when minting an
    /// introductory-offer-eligibility JWS for a user who has no prior App
    /// Store transactions. Returns null on iOS < 16.0 (where AppTransaction
    /// is unavailable) or if the AppTransaction is unverified.
    let appTransactionIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.in_app_purchase_storekit.InAppPurchase2API.appTransactionId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      appTransactionIdChannel.setMessageHandler { _, reply in
        api.appTransactionId { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      appTransactionIdChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol InAppPurchase2CallbackAPIProtocol {
  func onTransactionsUpdated(newTransactions newTransactionsArg: [SK2TransactionMessage], completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class InAppPurchase2CallbackAPI: InAppPurchase2CallbackAPIProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: StoreKit2MessagesPigeonCodec {
    return StoreKit2MessagesPigeonCodec.shared
  }
  func onTransactionsUpdated(newTransactions newTransactionsArg: [SK2TransactionMessage], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.in_app_purchase_storekit.InAppPurchase2CallbackAPI.onTransactionsUpdated\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([newTransactionsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
